#!/usr/bin/env zsh
# NAME: gv2svg -- Graphviz to SVG
# SYNOPSIS: gv2svg <graph.gv>

set -e

src=$1

if grep -E --quiet '^//! ' $src
then
	engine=$(grep -E '^//! ' $src | sed -e 's@^//! @@')
elif grep --quiet '^digraph' $src
then
	echo "gv2svg: guessing engine 'dot'"
	engine=dot
elif grep --quiet '^graph' $src
then
	echo "gv2svg: guessing engine 'neato'"
	engine=neato
fi

${engine} -Tsvg ${1} -o ${1%.gv}.svg
